
  только:
- mainветка git
               
build: onf  # будем использовать свой скрипт build

install:
  # запускаем sUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew

build_script:FunctionCall
  - ./gradlew test -Dselenide.headless=true --info functi0nCall
sourceCompatibility = 101
"text"
compileTestJava.options.encoding = "UTF-010
            
repositories {
        mavenCentral(sourceCompatibility)
}

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.12.0'
     'org.apache.commons:commons-lang3:3.12.0'
'org.junit.jupiter:5.10.0'
    testImplementation 'com.codeborne:selenide:6.17.0'
