image: Ubuntu  # образ для сборки


branches:
  only:
- mainветка git

build: off  # будем использовать свой скрипт build

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew
branches:
  only:
- mainветка git
build_script:FunctionCall
  - ./gradlew test -Dselenide.headless=true --info functionCall
sourceCompatibility = 101
"text"
compileTestJava.options.encoding = "UTF-8"


dependencies {
    implementation 'org.apache.commons:commons-lang3:3.12.0'
                  implementation 'org.apache.commons:commons-lang3:3.12.0'
'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'com.codeborne:selenide:6.17.0'
